<?php
return [
    'login_info'=>[
        'login_nologin_info' =>[
            'code'=>'0',
            'msg'=>'请先登录',
            'data'=>''
        ],
        'login_success_info' =>[
            'code'=>'1',
            'msg'=>'登录成功',
            'data'=>''
        ],
        'login_username_error_info'=>[
            'code'=>'0',
            'msg'=>'用户不存在',
            'data'=>''
        ],
        'login_usertype_error'=>[
            'code'=>'0',
            'msg'=>'用户类型错误',
            'data'=>''
        ],
        'login_userId_error'=>[
            'code'=>'0',
            'msg'=>'用户ID错误',
            'data'=>''
        ],
        'login_password_error'=>[
            'code'=>'0',
            'msg'=>'密码错误',
            'data'=>''
        ],
        'login_password2_error'=>[
            'code'=>'0',
            'msg'=>'两次密码不一致',
            'data'=>''
        ],
        'login_state_error'=>[
            'code'=>'0',
            'msg'=>'状态错误',
            'data'=>''
        ],
        'login_info_null'=>[
            'code'=>'0',
            'msg'=>'用户名或密码不能为空',
            'data'=>''
        ],
        'login_logout_suc'=>[
            'code'=>'1',
            'msg'=>'退出登录成功',
            'data'=>''
        ],
        'login_usertype_error'=>[
            'code'=>'0',
            'msg'=>'用户类型错误',
            'data'=>''
        ],
        'login_adminuser_error'=>[
            'code'=>'0',
            'msg'=>'非管理员用户不允许访问',
            'data'=>''
        ],
        'login_username_exit'=>[
            'code'=>'0',
            'msg'=>'已经存在该用户名',
            'data'=>''
        ],
    ],
    'global_info'=>[
        'global_operate_suc' =>[
            'code'=>'1',
            'msg'=>'操作成功',
            'data'=>''
        ],
        'global_operate_error' =>[
            'code'=>'0',
            'msg'=>'操作失败',
            'data'=>''
        ],
        'global_token_error'=>[
            'code'=>'0',
            'msg'=>'token错误',
            'data'=>''
        ],
        'global_data_suc'=>[//获取信息成功，返回信息
            'code'=>'1',
            'msg'=>'成功',
            'data'=>''
        ],
        'global_data_err'=>[//获取信息失败，返回信息
            'code'=>'0',
            'msg'=>'失败',
            'data'=>''
        ],
        'global_param_error'=>[//获取信息成功，返回信息
            'code'=>'0',
            'msg'=>'参数错误',
            'data'=>''
        ],
        'global_endtime_error'=>[//获取信息成功，返回信息
            'code'=>'0',
            'msg'=>'结束时间必须大于开始时间',
            'data'=>''
        ],
    ],
    'db_info'=>[
        ///修改时候只修改ID，提示此消息
        'db_noupdate_info' =>[
            'code'=>'1',
            'msg'=>'没有数据需要修改',
            'data'=>''
        ],
        'db_noid_info' =>[
            'code'=>'0',
            'msg'=>'ID为空',
            'data'=>''
        ],
        'db_exit_info' =>[
            'code'=>'0',
            'msg'=>'已经存在该值',
            'data'=>''
        ],
        'db_uniqe_info' =>[//判断是否已经存在该值
            'code'=>'1',
            'msg'=>'字段唯一',
            'data'=>''
        ],
        'db_tablename_err' =>[
            'code'=>'0',
            'msg'=>'表名错误',
            'data'=>''
        ],
        'db_add_suc'=>[
            'code'=>'1',
            'msg'=>'添加成功',
            'data'=>''
        ],
        'db_add_err'=>[
            'code'=>'0',
            'msg'=>'添加失败',
            'data'=>''
        ],
        'db_edit_suc'=>[
            'code'=>'1',
            'msg'=>'修改成功',
            'data'=>''
        ],
        'db_edit_err'=>[
            'code'=>'0',
            'msg'=>'修改失败',
            'data'=>''
        ],
        'db_delete_suc'=>[
            'code'=>'1',
            'msg'=>'删除成功',
            'data'=>''
        ],
        'db_delete_err'=>[
            'code'=>'0',
            'msg'=>'删除失败',
            'data'=>''
        ],
        'db_norecord_err'=>[
            'code'=>'0',
            'msg'=>'数据不存在',
            'data'=>''
        ],
    ],
    'file_info'=>[
        'file_nonfile_err'=>[//获取信息成功，返回信息
            'code'=>'0',
            'msg'=>'文件不存在',
            'data'=>''
        ],
        'file_exts_err' =>[
            'code'=>'0',
            'msg'=>'文件类型错误',
            'data'=>''
        ],
        'file_size_err' =>[
            'code'=>'0',
            'msg'=>'文件大小错误',
            'data'=>''
        ],
        'file_upload_err' =>[
            'code'=>'0',
            'msg'=>'文件上传失败',
            'data'=>''
        ],
        'file_save_err' =>[
            'code'=>'0',
            'msg'=>'文件保存失败',//保存到files表失败
            'data'=>''
        ],
        'file_upload_suc' =>[
            'code'=>'1',
            'msg'=>'上传成功',//保存到files表失败
            'data'=>''
        ],

    ]
];